import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import dynamic from "next/dynamic";
import Image from "next/image";
import { LineChartData } from "../utils/LineChartData";

const LineChart = dynamic(() => import("./LineChart"), {
  ssr: false,
});

const Home = () => {
  const [darkMode, setDarkMode] = useState(false);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${darkMode ? "dark" : ""}`}>
        <main className="bg-slate-200 min-h-screen dark:bg-gray-800 dark:text-white antialiased transition-colors duration-200">
          {/* <Image
            src="/bg-img.webp"
            alt="Background Image"
            width={100}
            height={100}
            className="w-full h-auto object-cover object-center"
          /> */}
          <h1 className="text-3xl font-bold text-red-500 dark:text-white ">
            Hello world!
          </h1>
          <button className="px-5 ">
            <BsFillMoonStarsFill
              className="text-xl"
              onClick={() => setDarkMode(!darkMode)}
            />
          </button>

          <button className=" bg-slate-500 p-2 rounded-md text-white font-medium dark:text-slate-800 dark:bg-sky-200">
            HELLO THERE
          </button>

          <div className="h-[500px] w-[500px] ">
            <h1 className="text-gray-800 font-bold text-2xl dark:text-white">
              Revenue
            </h1>
            <LineChart
              data={LineChartData}
              darkMode={darkMode}
            />
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
