import Head from "next/head";
import Dashboard from "../components/Dashboard";

const index = () => {
  return (
    <>
      <Head>
        <title>Dashboard | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Dashboard />
    </>
  );
};

export default index;
