import Head from "next/head";
import { useEffect } from "react";
import Dashboard from "../components/Dashboard";
import { RootState } from "../store/store";
import { useSelector } from "react-redux";

const index = () => {
  const darkMode = useSelector((state: RootState) => state.darkMode.value);

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", `${darkMode ? "dark" : "light"}`);
  }, [darkMode]);

  return (
    <>
      <Head>
        <title>Dashboard | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </>
  );
};

export default index;
